import { Estudante } from './estudante';

export const ESTUDANTES: Estudante[] = [
  {
    id: 1,
    nome: 'Roberto',
    curso: 'GTI',
    matricula: 199,
    nota: 8,
    materia: 'Banco de Dados',
    semestre: 3,
  },
  {
    id: 2,
    nome: 'Ferreira',
    curso: 'GTI',
    matricula: 201,
    nota: 10,
    materia: 'Banco de Dados',
    semestre: 3,
  },
  {
    id: 4,
    nome: 'Alckmin',
    curso: 'GTI',
    matricula: 189,
    nota: 9,
    materia: 'Algoritmo',
    semestre: 1,
  },
  {
    id: 5,
    nome: 'Brunelli',
    curso: 'GTI',
    matricula: 300,
    nota: 8,
    materia: 'PLA',
    semestre: 3,
  },
  {
    id: 6,
    nome: 'Vicente',
    curso: 'GTI',
    matricula: 403,
    nota: 8,
    materia: 'Redes',
    semestre: 3,
  },
  {
    id: 7,
    nome: 'Silva',
    curso: 'GTI',
    matricula: 899,
    nota: 7,
    materia: 'Banco de dados',
    semestre: 2,
  },
  {
    id: 8,
    nome: 'Binho',
    curso: 'GTI',
    matricula: 24,
    nota: 6,
    materia: 'Economia',
    semestre: 3,
  },
  {
    id: 9,
    nome: 'Nunes',
    curso: 'GTI',
    matricula: 187,
    nota: 8,
    materia: 'Economia',
    semestre: 3,
  },
  {
    id: 10,
    nome: 'Moreira',
    curso: 'GTI',
    matricula: 299,
    nota: 8,
    materia: 'Economia',
    semestre: 3,
  },
];
