import { Estudante } from './estudante';

export const ESTUDANTES: Estudante[] = [
  {
    id: 1,
    nome: 'Allan',
    curso: 'ADS',
    matricula: 534,
    nota: 8,
    materia: 'Eletiva Web',
    semestre: 3,
  },
  {
    id: 2,
    nome: 'André',
    curso: 'ADS',
    matricula: 567,
    nota: 10,
    materia: 'Eletiva Web',
    semestre: 3,
  },
  {
    id: 4,
    nome: 'Armando',
    curso: 'ADS',
    matricula: 234,
    nota: 9,
    materia: 'Algoritimo',
    semestre: 1,
  },
  {
    id: 5,
    nome: 'Lucas',
    curso: 'ADS',
    matricula: 645,
    nota: 8,
    materia: 'PLA',
    semestre: 3,
  },
  {
    id: 6,
    nome: 'Gustavo',
    curso: 'ADS',
    matricula: 867,
    nota: 8,
    materia: 'SO',
    semestre: 3,
  },
  {
    id: 7,
    nome: 'Vitor',
    curso: 'ADS',
    matricula: 890,
    nota: 7,
    materia: 'Banco de Dados',
    semestre: 2,
  },
  {
    id: 8,
    nome: 'Rafaela',
    curso: 'ADS',
    matricula: 889,
    nota: 6,
    materia: 'Eletiva Web',
    semestre: 3,
  },
  {
    id: 9,
    nome: 'Sandro',
    curso: 'ADS',
    matricula: 999,
    nota: 8,
    materia: 'Eletiva Web',
    semestre: 3,
  },
  {
    id: 10,
    nome: 'Jack',
    curso: 'ADS',
    matricula: 299,
    nota: 8,
    materia: 'Eletiva Web',
    semestre: 3,
  },
];
